#!/usr/bin/env python3

from subprocess import Popen, PIPE, STDOUT
import os

print("starting child")

subp_input = """1+1
3+4
9*2+3
"""


in_name = "testin.txt"
out_name= "testout.txt"

# with open("testin.txt","w") as f:
#   f.write(subp_input)

f = open(in_name,"w+")
f.write(subp_input)
f.seek(0)

subp = Popen(["bc","-iq"],
             stdin=f,
             stdout=PIPE,
             stderr=PIPE)



# print("communicating")
# (stdout, stderr) = subp.communicate(subp_input)

# stdout = stdout.decode()
# stderr = stderr.decode()

# print("writing to stdin for proc",subp.pid)
# subp.stdin.write(subp_input)
# subp.stdin.close()

print("waiting on proc",subp.pid)
subp.wait(timeout=3)

stdout = subp.stdout.read().decode()
stderr = subp.stderr.read().decode()

print("stdout:\n"+stdout)
print("stderr:\n"+stderr)

f.close()
os.remove("testin.txt")

with open(out_name,"w") as f:
  print(stdout,file=f)
  print(f"Output saved in {out_name}")


