#!/usr/bin/env python3

# from: https://docs.python.org/3/library/difflib.html#difflib.Differ

""" Command line interface to difflib.py providing diffs in four formats:

* ndiff:    lists every line and highlights interline changes.
* context:  highlights clusters of changes in a before/after format.
* unified:  highlights clusters of changes in an inline format.
* html:     generates side by side comparison with change highlights.

"""

import sys, os, difflib, argparse
from difflib import SequenceMatcher
from datetime import datetime, timezone

def sdiff(alines,blines):
    if type(alines) is str:
        alines = alines.splitlines()
    if type(blines) is str:
        blines = blines.splitlines()

    awidth = max(len(a) for a in alines)
    bwidth = max(len(a) for a in alines)

    cruncher = SequenceMatcher(None, alines, blines)
    difflines = []

    for tag, alo, ahi, blo, bhi in cruncher.get_opcodes():
        print(f"{tag} {alo} {ahi} {blo} {bhi}")
        if tag == 'replace':
            for i in range(alo,ahi):
                difflines.append(f"{alines[i]:{awidth}} | {blines[i]:{bwidth}}")
        elif tag == 'delete':
            for i in range(alo,ahi):
                difflines.append(f"{alines[i]:{awidth}} < {'':{bwidth}}")
        elif tag == 'insert':
            for i in range(blo,bhi):
                difflines.append(f"{'':{awidth}} > {blines[i]:{bwidth}}")
        elif tag == 'equal':
            for i in range(alo,ahi):
                difflines.append(f"{alines[i]:{awidth}}   {blines[i]:{bwidth}}")
        else:
            raise ValueError('unknown tag %r' % (tag,))

    difflines.append("")
    return "\n".join(difflines)


def file_mtime(path):
    t = datetime.fromtimestamp(os.stat(path).st_mtime,
                               timezone.utc)
    return t.astimezone().isoformat()

def main():

    parser = argparse.ArgumentParser()
    parser.add_argument('-c', action='store_true', default=False,
                        help='Produce a context format diff (default)')
    parser.add_argument('-u', action='store_true', default=False,
                        help='Produce a unified format diff')
    parser.add_argument('-s', action='store_true', default=False,
                        help='Produce a side-by-side format diff')
    parser.add_argument('-m', action='store_true', default=False,
                        help='Produce HTML side by side diff '
                             '(can use -c and -l in conjunction)')
    parser.add_argument('-n', action='store_true', default=False,
                        help='Produce a ndiff format diff')
    parser.add_argument('-l', '--lines', type=int, default=3,
                        help='Set number of context lines (default 3)')
    parser.add_argument('fromfile')
    parser.add_argument('tofile')
    options = parser.parse_args()

    n = options.lines
    fromfile = options.fromfile
    tofile = options.tofile

    fromdate = file_mtime(fromfile)
    todate = file_mtime(tofile)
    with open(fromfile) as ff:
        fromlines = ff.readlines()
    with open(tofile) as tf:
        tolines = tf.readlines()

    if options.u:
        diff = difflib.unified_diff(fromlines, tolines, fromfile, tofile, fromdate, todate, n=n)
    elif options.n:
        diff = difflib.ndiff(fromlines, tolines)
    elif options.s:
        diff = sdiff(open(fromfile).read(), open(tofile).read())
    elif options.m:
        diff = difflib.HtmlDiff().make_file(fromlines,tolines,fromfile,tofile,context=options.c,numlines=n)
    else:
        diff = difflib.context_diff(fromlines, tolines, fromfile, tofile, fromdate, todate, n=n)

    sys.stdout.writelines(diff)

if __name__ == '__main__':
    main()
