* Testy
A script to run tests for interactive terminal programs. Tests are
specified Emacs Org-like files.

* License
~testy~ is released under the terms of the *GNU General Public License
v3.0-or-later (GPLv3-or-later)*. A copy of the GPLv3-or-later is
included in the file ~LICENSE~ in the source repository.
  

* Planned Additions
- Remove the need to pass 'cat' as the filter to various
  TESTY_MULTI commands
- Adjust standard single tests to add failures to lists like they
  do in TESTY_MULT (refactoring)
- Explore use of Bash's built-in co-processes to see if that would
  simplify the overall design 
- Catch signals and clean up files if interrupt/term signal is given
- Add version number reporting
- Add documentation for TESTY_MULTI

* Completed Additions
- Add support for Valgrind: re-run previous test to check for valgrind
  results
- Added support for testing multiple programs at once via TESTY_MULTI
  which can launch multiple coordinate programs and check their
  behavior
- Add automatic regeneration of test results
  - LOW PRIORITY: the actual results for test are stored in files
    which can easily be re-inserted into the Org SRC blocks via
    commands in emacs.
- Re-checked example files in file:examples/ to guarantee that all of
  them work as expected
